apiVersion: v1
kind: Pod
metadata:
  name: rdma-test-pod-2
  annotations:
    k8s.v1.cni.cncf.io/networks: rdma-net-ipam
spec:
  nodeSelector:
    kubernetes.io/hostname: ubuntu00
  restartPolicy: OnFailure
  containers:
  - image: mellanox/rping-test 
    name: rdma-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK","NET_ADMIN" ]
    resources:
      limits:
        rdma/hca_shared_devices_a: 1
      requests:
        rdma/hca_shared_devices_a: 1
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/net
      sleep 1000000
