apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sriov-network-operator.fullname" . }}
  labels:
    {{- include "sriov-network-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sriov-network-operator
  template:
    metadata:
      labels:
        name: sriov-network-operator
    spec:
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sriov-network-operator.fullname" . }}
      containers:
        - name: sriov-network-operator
          image: {{ .Values.images.operator }}
          command:
          - sriov-network-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SRIOV_CNI_IMAGE
              value: {{ .Values.images.sriovCni }}
            - name: SRIOV_INFINIBAND_CNI_IMAGE
              value: {{ .Values.images.ibSriovCni | quote }}
            - name: SRIOV_DEVICE_PLUGIN_IMAGE
              value: {{ .Values.images.sriovDevicePlugin | quote }}
            - name: NETWORK_RESOURCES_INJECTOR_IMAGE
              value: ""
            - name: OPERATOR_NAME
              value: sriov-network-operator
            - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
              value: {{ .Values.images.sriovConfigDaemon | quote }}
            - name: SRIOV_NETWORK_WEBHOOK_IMAGE
              value: ""
            - name: RESOURCE_PREFIX
              value: openshift.io
            - name: ENABLE_ADMISSION_CONTROLLER
              value: "false"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELEASE_VERSION
              value: {{ .Release.AppVersion }}
            - name: SRIOV_CNI_BIN_PATH
              value: /opt/cni/bin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
